# Site settings
title: jandem's blog
description: > # this means to ignore newlines until "baseurl:"
  jandem's blog on Mozilla, SpiderMonkey, and more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jandemooij.nl" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]

gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"